# Check on http://lint.travis-ci.org/ after modifying it!
sudo: required
language: c
os:
  - linux
  - osx
env:
  - PYVERSION="3.5"
addons:
  apt:
    packages:
      - xvfb
before_install:
  - echo "$TRAVIS_OS_NAME"
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh; fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels https://conda.anaconda.org/biocore
  - conda config --add channels conda-forge
  - conda config --add channels bioconda
  # Update conda itself
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
install:
  - conda create -n test_env python=$PYVERSION --file ci/conda_requirements.txt
  - source activate test_env
  - pip install -r ci/pip_requirements.txt
  - pip install . --no-deps
before_script:
  - export DISPLAY=:99.0
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start; fi
script:
  - WITH_COVERAGE=TRUE make all
notifications:
  webhooks:
    on_success: change
    on_failure: always
after_success:
  - coveralls
