name: calour
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python
  - numpy
  - scipy
  - pyqt>=5
  - pandas
  - matplotlib>=2.0
  - scikit-learn>=0.19
  - scikit-bio>=0.5.1
  - biom-format
  - statsmodels
  - ipywidgets
  - pip
  - pip:
      - git+https://github.com/biocore/calour.git
      - git+https://github.com/amnona/dbbact-calour.git
